// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckFFmpeg() {
  return window['go']['main']['App']['CheckFFmpeg']();
}

export function Compress(arg1) {
  return window['go']['main']['App']['Compress'](arg1);
}

export function Convert(arg1) {
  return window['go']['main']['App']['Convert'](arg1);
}

export function InstallFFmpeg() {
  return window['go']['main']['App']['InstallFFmpeg']();
}

export function OpenInFolder(arg1) {
  return window['go']['main']['App']['OpenInFolder'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectOutputDir() {
  return window['go']['main']['App']['SelectOutputDir']();
}
