// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckFFmpeg():Promise<boolean>;

export function Compress(arg1:main.ProcessRequest):Promise<main.ProcessResult>;

export function Convert(arg1:main.ProcessRequest):Promise<main.ProcessResult>;

export function InstallFFmpeg():Promise<void>;

export function OpenInFolder(arg1:string):Promise<void>;

export function SelectFile():Promise<main.FileInfo>;

export function SelectOutputDir():Promise<string>;
